### ISSUE TITLE
response as json

### ISSUE THREAD

**Issue by Maharacha** [jakobilobi/wsstat#1]
would it make sense to make the response a json object instead? I want to run:
`wsstat -json rpc_methods wss://polkadot-rpc.dwellir.com | jq`

**Comment by jakobilobi** [comment]
Might indeed! Hmm perhaps it'll be a second flag though, like `-ro` for "response only".

**Comment by jakobilobi** [comment]
I added setting `-ro` in the latest release, [v0.1.1](https://github.com/jakobilobi/wsstat/releases/tag/v0.1.1). Try it out!
